# Generated by Django 3.2.5 on 2021-11-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnumber', models.CharField(blank=True, db_column='flightNumber', max_length=255, null=True)),
                ('operatingairlines', models.CharField(blank=True, db_column='operatingAirlines', max_length=255, null=True)),
                ('depaturecity', models.CharField(blank=True, db_column='depatureCity', max_length=255, null=True)),
                ('arrivalcity', models.CharField(blank=True, db_column='arrivalCity', max_length=255, null=True)),
                ('dateofdepature', models.DateField(blank=True, db_column='dateOfDepature', null=True)),
                ('estimatedtimeofdepatur', models.TimeField(blank=True, db_column='estimatedTimeOfDepatur', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, db_column='middleName', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.passenger')),
            ],
        ),
    ]
